//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGIPC_Website2
{


    public partial class gallery
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// pnlNotLoggedIn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNotLoggedIn;

        /// <summary>
        /// pnlLoggedIn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlLoggedIn;

        /// <summary>
        /// lblUserName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblUserName;

        /// <summary>
        /// pnlSidebarNotLoggedIn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlSidebarNotLoggedIn;

        /// <summary>
        /// pnlSidebarLoggedIn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlSidebarLoggedIn;

        /// <summary>
        /// lblSidebarUserName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSidebarUserName;

        /// <summary>
        /// btnAddAchievements control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnAddAchievements;

        /// <summary>
        /// btnAddWorkshops control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnAddWorkshops;

        /// <summary>
        /// btnAddTeamEvents control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnAddTeamEvents;
    }
}
